### ISSUE TITLE
Proposal: Domains in the Namecoin DNS should regularly go up for public auction.

### ISSUE THREAD

**Issue by fresheneesz** [namecoin/namecoin-legacy#181] opened 2014-09-21 23:39 UTC
The mainstream DNS system has a major problem: domain hoarding. Namecoin seems to provide very little that solves this problem. While namecoin has a small fee for registering domains, the fee is so small as to be negligible, and therefore is only slightly better than the current corrupt mainstream DNS system that allows domain hoarders to have domains essentially for free.

To combat this, I'm proposing an enforced public auction of domains that happens something like every 2 or 3 years for each domain. There are a couple important properties of the auction
- It should be enforced by the protocol (ie it should be inherent in the system that these auctions be honored)
- The current holder of a domain should be able to win the auction with a winning bid of more than only 1% of the highest 2nd-party bid. This is so that the cost of keeping a domain is related to demand, but is not a heavy burden on domain holders. For example, if the highest 2nd-party bid is 3 BTC/Namecoins, the current owner would win the auction with a bid of at least 0.03BTC/Namecoins.
- If the current holder of a domain wins the auction, they pay random active addresses in the blockchain (this is how registering domains in the first place should work too). Destroying the coins (which I believe is what namecoin currently does) seems like a destabilizing approach that could severely limit the system. Paying all active addresses would be ideal, but would almost definitely make the blockchain too large to handle.
- If a 2nd party in the auction wins, they pay the ex-current holder of the domain.

I realize namecoin may be too far-gone to actually implement this strategy, but I would appreciate people's thoughts about it anyway.

**Comment by domob1812** [comment] 2014-09-22 07:12
Hi!

On 2014-09-22 01:39, fresheneesz wrote:

> The mainstream DNS system has a major problem: domain hoarding. Namecoin
> seems to provide very little that solves this problem. While namecoin
> has a small fee for registering domains, the fee is so small as to be
> negligible, and therefore is only slightly better than the current
> corrupt mainstream DNS system that allows domain hoarders to have
> domains essentially for free.

This comes up every once in a while, but I don't actually believe that
squatting is such a bad problem in Namecoin as it is usually portraied
to be.

As a little challenge, do you know of any
company/individual/organisation that has their name squatted, contacted
the squatter, and was refused to get the domain for a reasonable price?

I believe that most of the current squatters in Namecoin are mostly
interested in Namecoin's long-term success and would rather see a domain
used to expand Namecoin than sit on it in hopes of extorting a high
price.  The problem is not squatters, the problem is that noone uses
.bit domains so far.

> To combat this, I'm proposing an enforced public auction of domains that
> happens something like every 2 or 3 years for each domain. There are a
> couple important properties of the auction
> ...

This or something very similar has been brought up already in
discussions.  While I can only state my own, personal opinion below, I
think to recall that others in the core community agreed with me (but
don't take my word for it).

I think that such a process is not good.  One of the core principles of
Namecoin is that it is uncensorable and unseizable.  Introducing such
"auctions" undermines this, as it introduces a way to effectively
"seize" a domain given enough resources.  And even if the current owner
has a 100x advantage, this may not be enough if it is "David vs
Goliath", like a government agency who's trying to censor Wikileaks or
Piratebay or something like that.  So from me that's a definite "no go".

Regarding "putting names to highest economic use" (as someone called
it), see my comments above.  Additionally, IMHO that's not the first and
foremost goal of Namecoin.  For companies, trademark holders and all
that, a centralised system like ICANN domains and trademark registries
is the way to go.  Namecoin is there for free speech instead.

> I realize namecoin may be too far-gone to actually implement this
> strategy, but I would appreciate people's thoughts about it anyway.

That's not true.  If there's an actual agreement among the community,
then it will be possible to implement changes (whatever they may be).
But I would strongly oppose the particular changes you propose for the
reasons outlined above, and believe that others will see it the same.

Yours,
Daniel

## 

http://www.domob.eu/
OpenPGP: 901C 5216 0537 1D2A F071  5A0E 4D94 6EED 04F7 CF52

## Namecoin: id/domob -> https://nameid.org/?name=domob

Done:  Arc-Bar-Cav-Hea-Kni-Ran-Rog-Sam-Tou-Val-Wiz
To go: Mon-Pri

**Comment by JeremyRand** [comment] 2014-09-22 07:40
Hi,

I agree with Daniel on all points, except this one:

"For companies, trademark holders and all that, a centralised system like ICANN domains and trademark registries is the way to go. Namecoin is there for free speech instead."

I'm of the opinion that most trademark holders will be able to use their trademarks in Namecoin without significant problems.  They may have to get their name from a squatter, but quite honestly, in most cases a large company has far more money at stake in their Namecoin name than any other entity, and can therefore get control of their name if the squatter's motive is profit.  E.g. even if I were a squatter only concerned with profit, and I weren't primarily worried about Namecoin's success, I still wouldn't be holding a single name hostage for absurd amounts of money, because my goal would be to make a net profit on all the names I hold, not hold out for a huge payout on one name.  If I were a profit-motivated squatter holding d/google, and Google offered to buy it for $1000, which is nothing to them, I'd be satisfied and happily hand it over, because that's a pretty good profit for a registration that cost me under a dollar and only a few minutes of time.  Google would probably be satisfied by such a sale too, assuming Namecoin was in high enough use that d/google could reach a large audience.

Now, in certain rare cases, someone will squat a name not for profit reasons but for specifically censorship or hijacking reasons.  E.g., if I absolutely hate Facebook and just want to cause them grief, or if I want to hijack Facebook connections, I could register d/facebook and simply redirect all connections to my own server, which might either redirect to a Facebook competitor, or steal Facebook passwords.  I generally think that these cases are best dealt with as a law enforcement problem and/or as a social problem rather than by introducing centralization.  Here are some options available to Facebook if this happens to them:
1. If an IP address is linked to in the name's value, look up who owns the IP address and send them a legal threat.
2. If someone is operating a business using the name, organize a boycott of the business.
3. Educate end users that a domain name doesn't always correspond to the same-named business.  This is already obvious in many cases: delta.com can't correspond to _both_ the airline and the hardware company.  And it's a logical position to take, in the same way that my name is Jeremy Rand, but if someone on the Internet mentions Jeremy Rand, they might be referring to me, or to someone else named Jeremy Rand.  Gmail is reportedly having to deal with this, in the sense that computer-illiterates assume that their firstname.lastname@gmail.com must route to their inbox.  But no one has filed a trademark lawsuit over such a collision (at least, I hope not).

A lot of the arguments against Namecoin made here are analogous to arguments made against other technologies that act as checks on power structures.  Tor is widely demonized by the illiterate as being primarily used by pedophiles, even though according to Ahmia.fi, only 9 websites with even possible child porn were found among the many thousands of .onion sites which were spidered.  Bitcoin is widely demonized as used for terrorist money laundering, even though it's responsible for improving quality of life in countries where politicians are the ones laundering money.  Anyone claiming that these criticisms warrant introducing censorship into Tor and Bitcoin would be dismissed as misguided (or perhaps evil, depending on who's making the claim).  I think by extension, the good done for society by having an uncensored naming system vastly outweighs the minor reorganizations which society's most powerful entities will have to undergo to counter squatting.

Full disclosure: I'm holding something like 100 names which I will happily hand over to the entity named, free of charge, upon request.  So far no one's asked.

**Comment by phelixbtc** [comment] 2014-09-22 08:29
This is a discussion that should be continued on the forum. Feel free to copy paste your posts to a new/old thread on the forum. Closing.

**Closed as completed by phelixbtc** 2014-09-22 08:29 UTC

**Comment by fresheneesz** [comment] 2014-09-22 08:42
I have, in fact, myself contacted a few domain squatters who refused to give me a reasonable price (sub $1000). So this isn't just some theoretical problem. Its very real.

"most of the current squatters in Namecoin are mostly interested in Namecoin's long-term success"

I don't actually care what current squatters are squatting for. I'm more interested in the end-game usage of namecoin - once its gone into mainstream use. The only reason we should want namecoin to become successful is that we think it will be significantly better once in mainstream use (whether or not its useful before then).

"One of the core principles of Namecoin is that it is uncensorable and unseizable."

That is a good point. While I'm not sure I consider domain names "speech" and therefore I'm not sure censorship is really the right concept here, it is a powerful idea that you can have and own a domain indefinitely without the possibility of someone taking it from you by force. This brings up a tangential question tho: can a namecoin domain be "lost" like bitcoins can be lost? I imagine so. In that case, an auction would prevent the possibility of names being lost forever.

Also, the 100x amount was just an example value really. The important properties of whatever ratio is chosen is that its low enough to prevent squatters from making money by buying thousands of domains and holding them ad infinitum - selling only a few for an outrageous price. But your point brings up an equally important constraint - that the number be high enough to prevent hostile domain snatching. Do you believe that the ratio low enough to prevent squatters is below the number high enough to prevent hostile domain snatching? I believe there is a range that solves both problems. Maybe 1000% is the right number, maybe 10000%.

Also, because the money from a purchase of a domain goes to the previous/current domain holder, if that ratio is high enough, people who actually want to keep the domain may be swayed just by the money. At very least its a consolation prize. Also, if they are being attacked by censors, the large amount of money it takes might greatly deter them from trying to snatch their domain. If they have to give $10'000 to their enemy just to take their domain.. they may be doing more benefit than damage. 

What ratio do you think is high enough to prevent goliath from beating david?

"ICANN domains and trademark registries is the way to go"

ICANN is only the way to go for people who can put pressure on the ICANN group. Suffice it to say, ICANN domains will _not_ be the way to go for 99.9999% of domain holders if there is a viable alternative (like namecoin). Any central authority is a monopoly with all the related cons. I think namecoin as it stands (even with the squatting issues) is better than ICANN in all respects. I just want to see it do even better ; )

"a large company has far more money at stake in their Namecoin name than any other entity"

And what about a small company? Why do you inadvertently that somehow only large companies buy domains? I'm primarily interested in this stuff because of the cost and annoyance of finding and paying for domains for my own personal use, as well as the cost of buying TLS certificates for the company I'm starting. The downsides of namecoin's current design should not be dismissed because "who cares about those big companies - they have enough money to deal with it". The little guy won't have those resources.

I think I might need to explain how domain squatters operate. Domain squatters buy tens of thousands of domains (with the current system, essentially for free using the "free-trial" loophole only they have access to) and hold them util someone will pay an exorbitant amount of money for it. They would make money for selling domains for $5, but they won't sell for anything less than $1000 because they make more money that way. They essentially create a shortage, and capitalize on it. This is so evil, and its disappointing that the namecoin community thinks it isn't a problem worth solving.

"rather than by introducing centralization"

I want to make it very clear that I am in no way proposing any kind of centralization. The auctions would be done in a decentralized way as part of the protocol itself. 

@phelixbtc I'll create a forum post once i get the account creation email.

**Comment by fresheneesz** [comment] 2014-09-22 08:51
@phelixbtc Um, so apparently I can't post in the forum? Whats the point of registering if I can't post? Is this the forum you were talking about: https://forum.namecoin.info/viewforum.php?f=22 ?

**Comment by fresheneesz** [comment] 2014-09-22 09:05
@phelixbtc I have to say, the forum is so early 90s. Github has a much better interface. Why not let the discussion happen here?

**Comment by JeremyRand** [comment] 2014-09-22 09:21
I'd actually support having a separate GitHub repo for this kind of discussions.  It doesn't belong in this repo, but I agree that the forum is a kind of clunky place to have these discussions.  (Note that I haven't really formally proposed that idea to the other devs, nor gotten feedback, so don't quote on on this.)

**Comment by phelixbtc** [comment] 2014-09-22 09:30
@fresheneesz To prevent spam you need to add yourself to the group of normal users. It should have told you so at some point during the registration.

**Comment by fresheneesz** [comment] 2014-09-22 10:12
@phelixbtc Thanks that worked. Gotta say tho, that is incredibly unintuitive.

@JeremyRand @domob1812  I made a post here: https://forum.namecoin.info/viewtopic.php?f=11&t=2003
