### ISSUE TITLE
A name_update of 1023 chars and domain is lost

### ISSUE THREAD

**Issue by khalahan** [namecoin/namecoin-legacy#3] opened 2011-10-21 09:46 UTC
After a name_update with 1023 chars, next operations result in :
`{"code":-1,"message":"could not sign name coin output"}`

See : https://dot-bit.org/forum/viewtopic.php?f=7&t=318
I've confirmed the bug on testnet too.

**Comment by khalahan** [comment] 2012-05-30 20:44
This line should not return false :
https://github.com/khalahan/namecoin/blob/1f2421d531c74fe290ff5bac90d9d528070b48e6/src/script.cpp#L1158

**Comment by khalahan** [comment] 2012-05-31 22:07
A name_update will fail if previous value was more than 520 characters... Sad...
See http://dot-bit.org/forum/viewtopic.php?f=2&t=503

**Comment by muneeb-ali** [comment] 2014-03-17 16:59
This bug should be marked critical, IMO -- I've personally "lost" a few names because of this bug. A simple fix is to just reject input in both name_firstupdate() and in name_update() that is > 519 bytes. Also, namecoin documentation should reflect this limit instead of saying 1023 bytes. 

Also, can someone share more details on the bug here? So others (including me) can try to fix the bug in namecoin itself? Thanks,

**Comment by phelixbtc** [comment] 2014-05-15 07:49
Are we good on this by now?

**Comment by domob1812** [comment] 2014-05-15 07:58
I think the consensus is that we should add the check to name_firstupdate and name_update to disallow too long values (according to snailbrain, there's already a check in the UI).  The fork for actually allowing values up to 1023 bytes (if we really want that?) will be done later when we have discussed value length & fees a bit more.

@muneeb-ali: AFAIK, the problem is that Bitcoin's scripting system doesn't allow values larger than 520 bytes on the stack and fails when it encounters them.  This leads to a failing signature check in the name_update if the name's value (which is part of the tx output script) is too large.

**Comment by domob1812** [comment] 2014-05-15 07:58
BTW, can someone confirm what the actual maximum _allowed_ length is?  519 bytes?  520 bytes?  Then I will add the check to the RPC commands.

**Comment by domob1812** [comment] 2014-06-16 08:06
Note that this was 'fixed' in the sense that the RPC commands now verify their input and only allow values up to (including) 520 characters.  Should we close this issue?

**Comment by phelixbtc** [comment] 2014-06-16 09:08
Maybe we should discuss this first on the forum...

**Comment by JeremyRand** [comment] 2014-08-19 23:12
I would support closing this.  The risk of losing a name is resolved, and increasing the value size is a much more complex issue that should be discussed separately.

**Comment by ryancdotorg** [comment] 2014-08-24 01:42
agree, close it

**Comment by JeremyRand** [comment] 2014-08-24 01:45
Closing, thanks Ryan.

**Closed as completed by JeremyRand** 2014-08-24 01:45 UTC

**Comment by phelixbtc** [comment] 2014-08-24 08:35
For the record: values of up to 1023 can be created but after that the name must expire.
